name: Run Selenium Java Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Verify Chrome Installation
      run: chrome --version

    - name: Run Maven Tests
      run: mvn clean test
